// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: confessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptConfession = `-- name: AcceptConfession :one
UPDATE confessions
SET status = 'accepted', post_ts = $2, post_thread_ts = $3, updated_at = now()
WHERE id = $1
RETURNING id, post_channel, text, status, created_at, updated_at, reply_key, review_ts, post_ts, post_thread_ts
`

type AcceptConfessionParams struct {
	ID           int64
	PostTs       pgtype.Text
	PostThreadTs pgtype.Text
}

func (q *Queries) AcceptConfession(ctx context.Context, arg AcceptConfessionParams) (Confession, error) {
	row := q.db.QueryRow(ctx, acceptConfession, arg.ID, arg.PostTs, arg.PostThreadTs)
	var i Confession
	err := row.Scan(
		&i.ID,
		&i.PostChannel,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplyKey,
		&i.ReviewTs,
		&i.PostTs,
		&i.PostThreadTs,
	)
	return i, err
}

const createConfession = `-- name: CreateConfession :one
INSERT INTO confessions (text, reply_key, post_channel)
VALUES ($1, $2, $3)
RETURNING id, post_channel, text, status, created_at, updated_at, reply_key, review_ts, post_ts, post_thread_ts
`

type CreateConfessionParams struct {
	Text        string
	ReplyKey    string
	PostChannel string
}

func (q *Queries) CreateConfession(ctx context.Context, arg CreateConfessionParams) (Confession, error) {
	row := q.db.QueryRow(ctx, createConfession, arg.Text, arg.ReplyKey, arg.PostChannel)
	var i Confession
	err := row.Scan(
		&i.ID,
		&i.PostChannel,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplyKey,
		&i.ReviewTs,
		&i.PostTs,
		&i.PostThreadTs,
	)
	return i, err
}

const deleteConfession = `-- name: DeleteConfession :exec
DELETE FROM confessions
WHERE id = $1
`

func (q *Queries) DeleteConfession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteConfession, id)
	return err
}

const getConfessionByID = `-- name: GetConfessionByID :one
SELECT id, post_channel, text, status, created_at, updated_at, reply_key, review_ts, post_ts, post_thread_ts FROM confessions
WHERE id = $1
`

func (q *Queries) GetConfessionByID(ctx context.Context, id int64) (Confession, error) {
	row := q.db.QueryRow(ctx, getConfessionByID, id)
	var i Confession
	err := row.Scan(
		&i.ID,
		&i.PostChannel,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplyKey,
		&i.ReviewTs,
		&i.PostTs,
		&i.PostThreadTs,
	)
	return i, err
}

const getConfessionByReplyKey = `-- name: GetConfessionByReplyKey :one
SELECT id, post_channel, text, status, created_at, updated_at, reply_key, review_ts, post_ts, post_thread_ts FROM confessions
WHERE reply_key = $1
`

func (q *Queries) GetConfessionByReplyKey(ctx context.Context, replyKey string) (Confession, error) {
	row := q.db.QueryRow(ctx, getConfessionByReplyKey, replyKey)
	var i Confession
	err := row.Scan(
		&i.ID,
		&i.PostChannel,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplyKey,
		&i.ReviewTs,
		&i.PostTs,
		&i.PostThreadTs,
	)
	return i, err
}

const rejectConfession = `-- name: RejectConfession :one
UPDATE confessions
SET status = 'rejected', updated_at = now()
WHERE id = $1
RETURNING id, post_channel, text, status, created_at, updated_at, reply_key, review_ts, post_ts, post_thread_ts
`

func (q *Queries) RejectConfession(ctx context.Context, id int64) (Confession, error) {
	row := q.db.QueryRow(ctx, rejectConfession, id)
	var i Confession
	err := row.Scan(
		&i.ID,
		&i.PostChannel,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplyKey,
		&i.ReviewTs,
		&i.PostTs,
		&i.PostThreadTs,
	)
	return i, err
}

const setConfessionReviewTs = `-- name: SetConfessionReviewTs :one
UPDATE confessions
SET review_ts = $2, updated_at = now()
WHERE id = $1
RETURNING id, post_channel, text, status, created_at, updated_at, reply_key, review_ts, post_ts, post_thread_ts
`

type SetConfessionReviewTsParams struct {
	ID       int64
	ReviewTs pgtype.Text
}

func (q *Queries) SetConfessionReviewTs(ctx context.Context, arg SetConfessionReviewTsParams) (Confession, error) {
	row := q.db.QueryRow(ctx, setConfessionReviewTs, arg.ID, arg.ReviewTs)
	var i Confession
	err := row.Scan(
		&i.ID,
		&i.PostChannel,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplyKey,
		&i.ReviewTs,
		&i.PostTs,
		&i.PostThreadTs,
	)
	return i, err
}

const undoConfession = `-- name: UndoConfession :one
UPDATE confessions
SET status = 'pending', post_ts = NULL, post_thread_ts = NULL, updated_at = now()
WHERE id = $1
RETURNING id, post_channel, text, status, created_at, updated_at, reply_key, review_ts, post_ts, post_thread_ts
`

func (q *Queries) UndoConfession(ctx context.Context, id int64) (Confession, error) {
	row := q.db.QueryRow(ctx, undoConfession, id)
	var i Confession
	err := row.Scan(
		&i.ID,
		&i.PostChannel,
		&i.Text,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReplyKey,
		&i.ReviewTs,
		&i.PostTs,
		&i.PostThreadTs,
	)
	return i, err
}
