// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Confession struct {
	ID          int64
	PostChannel string
	Text        string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ReplyKey    string
	ReviewTs    pgtype.Text
	PostTs      pgtype.Text
}
